CREATE TABLE  "USERMANAGEMENT" 
   (	"ADMIN_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(5,0), 
	"USERNAME" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(20), 
	"PROFILE_ID" NUMBER(3,0), 
	 CONSTRAINT "USERMANAGEMENT_PK" PRIMARY KEY ("USER_ID") ENABLE
   ) ;ALTER TABLE  "USERMANAGEMENT" ADD CONSTRAINT "USERMANAGEMENT_CON" FOREIGN KEY ("USER_ID")
	  REFERENCES  "USER_INFO" ("USER_ID") ON DELETE CASCADE ENABLE;


CREATE OR REPLACE TRIGGER  "BI_USERMANAGEMENT" 
  before insert on "USERMANAGEMENT"               
  for each row  
begin   
  if :NEW."ADMIN_ID" is null then 
    select "USERMANAGEMENT_SEQ".nextval into :NEW."ADMIN_ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_USERMANAGEMENT" ENABLE;


